

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureDroppedCallback(
				UniffiForeignFutureDroppedCallback cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static uint64_t call_UniffiCallbackInterfaceClone(
				UniffiCallbackInterfaceClone cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureResultU8 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureResultU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureResultI8 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureResultI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureResultU16 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureResultU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureResultI16 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureResultI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureResultU32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureResultU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureResultI32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureResultI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureResultU64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureResultU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureResultI64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureResultI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureResultF32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureResultF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureResultF64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureResultF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureResultRustBuffer result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureResultRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureResultVoid result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureResultVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EPHEMERAL_STREAM_CALLBACK_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EPHEMERAL_STREAM_CALLBACK_METHOD0
typedef void (*UniffiCallbackInterfaceEphemeralStreamCallbackMethod0)(uint64_t uniffi_handle, uint64_t message, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceEphemeralStreamCallbackMethod0(
				UniffiCallbackInterfaceEphemeralStreamCallbackMethod0 cb, uint64_t uniffi_handle, uint64_t message, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, message, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_TOPIC_STREAM_CALLBACK_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_TOPIC_STREAM_CALLBACK_METHOD0
typedef void (*UniffiCallbackInterfaceTopicStreamCallbackMethod0)(uint64_t uniffi_handle, RustBuffer event, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceTopicStreamCallbackMethod0(
				UniffiCallbackInterfaceTopicStreamCallbackMethod0 cb, uint64_t uniffi_handle, RustBuffer event, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, event, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_TOPIC_STREAM_CALLBACK_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_TOPIC_STREAM_CALLBACK_METHOD1
typedef void (*UniffiCallbackInterfaceTopicStreamCallbackMethod1)(uint64_t uniffi_handle, RustBuffer error, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceTopicStreamCallbackMethod1(
				UniffiCallbackInterfaceTopicStreamCallbackMethod1 cb, uint64_t uniffi_handle, RustBuffer error, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, error, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_TOPIC_STREAM_CALLBACK_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_TOPIC_STREAM_CALLBACK_METHOD2
typedef void (*UniffiCallbackInterfaceTopicStreamCallbackMethod2)(uint64_t uniffi_handle, uint64_t processed, RustBuffer source, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceTopicStreamCallbackMethod2(
				UniffiCallbackInterfaceTopicStreamCallbackMethod2 cb, uint64_t uniffi_handle, uint64_t processed, RustBuffer source, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, processed, source, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EPHEMERAL_STREAM_CALLBACK
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EPHEMERAL_STREAM_CALLBACK
typedef struct UniffiVTableCallbackInterfaceEphemeralStreamCallback {
    UniffiCallbackInterfaceFree uniffiFree;
    UniffiCallbackInterfaceClone uniffiClone;
    UniffiCallbackInterfaceEphemeralStreamCallbackMethod0 onMessage;
} UniffiVTableCallbackInterfaceEphemeralStreamCallback;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_TOPIC_STREAM_CALLBACK
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_TOPIC_STREAM_CALLBACK
typedef struct UniffiVTableCallbackInterfaceTopicStreamCallback {
    UniffiCallbackInterfaceFree uniffiFree;
    UniffiCallbackInterfaceClone uniffiClone;
    UniffiCallbackInterfaceTopicStreamCallbackMethod0 onEvent;
    UniffiCallbackInterfaceTopicStreamCallbackMethod1 onError;
    UniffiCallbackInterfaceTopicStreamCallbackMethod2 onOperation;
} UniffiVTableCallbackInterfaceTopicStreamCallback;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_NODEBUILDER
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_NODEBUILDER
uint64_t uniffi_p2panda_ffi_fn_clone_nodebuilder(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_NODEBUILDER
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_NODEBUILDER
void uniffi_p2panda_ffi_fn_free_nodebuilder(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_NODEBUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_NODEBUILDER_NEW
uint64_t uniffi_p2panda_ffi_fn_constructor_nodebuilder_new(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_ACK_POLICY
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_ACK_POLICY
void uniffi_p2panda_ffi_fn_method_nodebuilder_ack_policy(uint64_t ptr, RustBuffer ack_policy, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_BIND_IP_V4
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_BIND_IP_V4
void uniffi_p2panda_ffi_fn_method_nodebuilder_bind_ip_v4(uint64_t ptr, RustBuffer ip_address, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_BIND_IP_V6
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_BIND_IP_V6
void uniffi_p2panda_ffi_fn_method_nodebuilder_bind_ip_v6(uint64_t ptr, RustBuffer ip_address, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_BIND_PORT_V4
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_BIND_PORT_V4
void uniffi_p2panda_ffi_fn_method_nodebuilder_bind_port_v4(uint64_t ptr, uint16_t port, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_BIND_PORT_V6
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_BIND_PORT_V6
void uniffi_p2panda_ffi_fn_method_nodebuilder_bind_port_v6(uint64_t ptr, uint16_t port, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_BOOTSTRAP
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_BOOTSTRAP
void uniffi_p2panda_ffi_fn_method_nodebuilder_bootstrap(uint64_t ptr, uint64_t node_id, uint64_t relay_url, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_DATABASE_URL
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_DATABASE_URL
void uniffi_p2panda_ffi_fn_method_nodebuilder_database_url(uint64_t ptr, RustBuffer url, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_MDNS_MODE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_MDNS_MODE
void uniffi_p2panda_ffi_fn_method_nodebuilder_mdns_mode(uint64_t ptr, RustBuffer mode, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_NETWORK_ID
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_NETWORK_ID
void uniffi_p2panda_ffi_fn_method_nodebuilder_network_id(uint64_t ptr, uint64_t network_id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_PRIVATE_KEY
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_PRIVATE_KEY
void uniffi_p2panda_ffi_fn_method_nodebuilder_private_key(uint64_t ptr, uint64_t private_key, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_RELAY_URL
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_RELAY_URL
void uniffi_p2panda_ffi_fn_method_nodebuilder_relay_url(uint64_t ptr, uint64_t url, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_SPAWN
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODEBUILDER_SPAWN
uint64_t uniffi_p2panda_ffi_fn_method_nodebuilder_spawn(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_CURSOR
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_CURSOR
uint64_t uniffi_p2panda_ffi_fn_clone_cursor(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_CURSOR
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_CURSOR
void uniffi_p2panda_ffi_fn_free_cursor(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_CURSOR_NAME
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_CURSOR_NAME
RustBuffer uniffi_p2panda_ffi_fn_method_cursor_name(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_HASH
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_HASH
uint64_t uniffi_p2panda_ffi_fn_clone_hash(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_HASH
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_HASH
void uniffi_p2panda_ffi_fn_free_hash(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_HASH_DIGEST
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_HASH_DIGEST
uint64_t uniffi_p2panda_ffi_fn_constructor_hash_digest(RustBuffer value, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_HASH_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_HASH_FROM_BYTES
uint64_t uniffi_p2panda_ffi_fn_constructor_hash_from_bytes(RustBuffer value, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_HASH_FROM_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_HASH_FROM_HEX
uint64_t uniffi_p2panda_ffi_fn_constructor_hash_from_hex(RustBuffer value, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HASH_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HASH_TO_BYTES
RustBuffer uniffi_p2panda_ffi_fn_method_hash_to_bytes(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HASH_TO_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HASH_TO_HEX
RustBuffer uniffi_p2panda_ffi_fn_method_hash_to_hex(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_HEADER
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_HEADER
uint64_t uniffi_p2panda_ffi_fn_clone_header(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_HEADER
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_HEADER
void uniffi_p2panda_ffi_fn_free_header(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_BACKLINK
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_BACKLINK
RustBuffer uniffi_p2panda_ffi_fn_method_header_backlink(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_HASH
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_HASH
uint64_t uniffi_p2panda_ffi_fn_method_header_hash(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_LOG_ID
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_LOG_ID
uint64_t uniffi_p2panda_ffi_fn_method_header_log_id(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_PAYLOAD_HASH
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_PAYLOAD_HASH
uint64_t uniffi_p2panda_ffi_fn_method_header_payload_hash(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_PAYLOAD_SIZE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_PAYLOAD_SIZE
uint64_t uniffi_p2panda_ffi_fn_method_header_payload_size(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_PRUNE_FLAG
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_PRUNE_FLAG
int8_t uniffi_p2panda_ffi_fn_method_header_prune_flag(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_PUBLIC_KEY
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_PUBLIC_KEY
uint64_t uniffi_p2panda_ffi_fn_method_header_public_key(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_SEQ_NUM
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_SEQ_NUM
uint64_t uniffi_p2panda_ffi_fn_method_header_seq_num(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_SIGNATURE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_SIGNATURE
uint64_t uniffi_p2panda_ffi_fn_method_header_signature(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_TIMESTAMP
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_TIMESTAMP
uint64_t uniffi_p2panda_ffi_fn_method_header_timestamp(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_VERSION
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_HEADER_VERSION
uint64_t uniffi_p2panda_ffi_fn_method_header_version(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_NETWORKID
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_NETWORKID
uint64_t uniffi_p2panda_ffi_fn_clone_networkid(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_NETWORKID
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_NETWORKID
void uniffi_p2panda_ffi_fn_free_networkid(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_NETWORKID_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_NETWORKID_FROM_BYTES
uint64_t uniffi_p2panda_ffi_fn_constructor_networkid_from_bytes(RustBuffer value, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_NETWORKID_FROM_HASH
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_NETWORKID_FROM_HASH
uint64_t uniffi_p2panda_ffi_fn_constructor_networkid_from_hash(uint64_t hash, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_NETWORKID_FROM_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_NETWORKID_FROM_HEX
uint64_t uniffi_p2panda_ffi_fn_constructor_networkid_from_hex(RustBuffer value, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_NETWORKID_RANDOM
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_NETWORKID_RANDOM
uint64_t uniffi_p2panda_ffi_fn_constructor_networkid_random(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NETWORKID_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NETWORKID_TO_BYTES
RustBuffer uniffi_p2panda_ffi_fn_method_networkid_to_bytes(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NETWORKID_TO_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NETWORKID_TO_HEX
RustBuffer uniffi_p2panda_ffi_fn_method_networkid_to_hex(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_PRIVATEKEY
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_PRIVATEKEY
uint64_t uniffi_p2panda_ffi_fn_clone_privatekey(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_PRIVATEKEY
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_PRIVATEKEY
void uniffi_p2panda_ffi_fn_free_privatekey(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_PRIVATEKEY_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_PRIVATEKEY_FROM_BYTES
uint64_t uniffi_p2panda_ffi_fn_constructor_privatekey_from_bytes(RustBuffer value, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_PRIVATEKEY_FROM_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_PRIVATEKEY_FROM_HEX
uint64_t uniffi_p2panda_ffi_fn_constructor_privatekey_from_hex(RustBuffer value, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_PRIVATEKEY_GENERATE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_PRIVATEKEY_GENERATE
uint64_t uniffi_p2panda_ffi_fn_constructor_privatekey_generate(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PRIVATEKEY_PUBLIC_KEY
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PRIVATEKEY_PUBLIC_KEY
uint64_t uniffi_p2panda_ffi_fn_method_privatekey_public_key(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PRIVATEKEY_SIGN
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PRIVATEKEY_SIGN
uint64_t uniffi_p2panda_ffi_fn_method_privatekey_sign(uint64_t ptr, RustBuffer bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PRIVATEKEY_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PRIVATEKEY_TO_BYTES
RustBuffer uniffi_p2panda_ffi_fn_method_privatekey_to_bytes(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PRIVATEKEY_TO_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PRIVATEKEY_TO_HEX
RustBuffer uniffi_p2panda_ffi_fn_method_privatekey_to_hex(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_PUBLICKEY
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_PUBLICKEY
uint64_t uniffi_p2panda_ffi_fn_clone_publickey(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_PUBLICKEY
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_PUBLICKEY
void uniffi_p2panda_ffi_fn_free_publickey(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_PUBLICKEY_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_PUBLICKEY_FROM_BYTES
uint64_t uniffi_p2panda_ffi_fn_constructor_publickey_from_bytes(RustBuffer value, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_PUBLICKEY_FROM_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_PUBLICKEY_FROM_HEX
uint64_t uniffi_p2panda_ffi_fn_constructor_publickey_from_hex(RustBuffer value, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PUBLICKEY_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PUBLICKEY_TO_BYTES
RustBuffer uniffi_p2panda_ffi_fn_method_publickey_to_bytes(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PUBLICKEY_TO_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PUBLICKEY_TO_HEX
RustBuffer uniffi_p2panda_ffi_fn_method_publickey_to_hex(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PUBLICKEY_VERIFY
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PUBLICKEY_VERIFY
int8_t uniffi_p2panda_ffi_fn_method_publickey_verify(uint64_t ptr, RustBuffer bytes, uint64_t signature, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_RELAYURL
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_RELAYURL
uint64_t uniffi_p2panda_ffi_fn_clone_relayurl(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_RELAYURL
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_RELAYURL
void uniffi_p2panda_ffi_fn_free_relayurl(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_RELAYURL_FROM_STR
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_RELAYURL_FROM_STR
uint64_t uniffi_p2panda_ffi_fn_constructor_relayurl_from_str(RustBuffer value, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_RELAYURL_TO_STR
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_RELAYURL_TO_STR
RustBuffer uniffi_p2panda_ffi_fn_method_relayurl_to_str(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_SIGNATURE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_SIGNATURE
uint64_t uniffi_p2panda_ffi_fn_clone_signature(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_SIGNATURE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_SIGNATURE
void uniffi_p2panda_ffi_fn_free_signature(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_SIGNATURE_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_SIGNATURE_FROM_BYTES
uint64_t uniffi_p2panda_ffi_fn_constructor_signature_from_bytes(RustBuffer value, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_SIGNATURE_FROM_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_SIGNATURE_FROM_HEX
uint64_t uniffi_p2panda_ffi_fn_constructor_signature_from_hex(RustBuffer value, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_SIGNATURE_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_SIGNATURE_TO_BYTES
RustBuffer uniffi_p2panda_ffi_fn_method_signature_to_bytes(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_SIGNATURE_TO_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_SIGNATURE_TO_HEX
RustBuffer uniffi_p2panda_ffi_fn_method_signature_to_hex(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_TOPICID
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_TOPICID
uint64_t uniffi_p2panda_ffi_fn_clone_topicid(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_TOPICID
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_TOPICID
void uniffi_p2panda_ffi_fn_free_topicid(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_TOPICID_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_TOPICID_FROM_BYTES
uint64_t uniffi_p2panda_ffi_fn_constructor_topicid_from_bytes(RustBuffer value, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_TOPICID_FROM_HASH
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_TOPICID_FROM_HASH
uint64_t uniffi_p2panda_ffi_fn_constructor_topicid_from_hash(uint64_t hash, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_TOPICID_FROM_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_TOPICID_FROM_HEX
uint64_t uniffi_p2panda_ffi_fn_constructor_topicid_from_hex(RustBuffer value, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_TOPICID_RANDOM
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_TOPICID_RANDOM
uint64_t uniffi_p2panda_ffi_fn_constructor_topicid_random(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_TOPICID_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_TOPICID_TO_BYTES
RustBuffer uniffi_p2panda_ffi_fn_method_topicid_to_bytes(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_TOPICID_TO_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_TOPICID_TO_HEX
RustBuffer uniffi_p2panda_ffi_fn_method_topicid_to_hex(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_EPHEMERALMESSAGE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_EPHEMERALMESSAGE
uint64_t uniffi_p2panda_ffi_fn_clone_ephemeralmessage(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_EPHEMERALMESSAGE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_EPHEMERALMESSAGE
void uniffi_p2panda_ffi_fn_free_ephemeralmessage(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EPHEMERALMESSAGE_AUTHOR
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EPHEMERALMESSAGE_AUTHOR
uint64_t uniffi_p2panda_ffi_fn_method_ephemeralmessage_author(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EPHEMERALMESSAGE_BODY
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EPHEMERALMESSAGE_BODY
RustBuffer uniffi_p2panda_ffi_fn_method_ephemeralmessage_body(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EPHEMERALMESSAGE_TIMESTAMP
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EPHEMERALMESSAGE_TIMESTAMP
uint64_t uniffi_p2panda_ffi_fn_method_ephemeralmessage_timestamp(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EPHEMERALMESSAGE_TOPIC
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EPHEMERALMESSAGE_TOPIC
uint64_t uniffi_p2panda_ffi_fn_method_ephemeralmessage_topic(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_EPHEMERALSTREAM
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_EPHEMERALSTREAM
uint64_t uniffi_p2panda_ffi_fn_clone_ephemeralstream(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_EPHEMERALSTREAM
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_EPHEMERALSTREAM
void uniffi_p2panda_ffi_fn_free_ephemeralstream(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EPHEMERALSTREAM_PUBLISH
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EPHEMERALSTREAM_PUBLISH
uint64_t uniffi_p2panda_ffi_fn_method_ephemeralstream_publish(uint64_t ptr, RustBuffer message
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EPHEMERALSTREAM_TOPIC
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EPHEMERALSTREAM_TOPIC
uint64_t uniffi_p2panda_ffi_fn_method_ephemeralstream_topic(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_EPHEMERALSTREAMCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_EPHEMERALSTREAMCALLBACK
uint64_t uniffi_p2panda_ffi_fn_clone_ephemeralstreamcallback(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_EPHEMERALSTREAMCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_EPHEMERALSTREAMCALLBACK
void uniffi_p2panda_ffi_fn_free_ephemeralstreamcallback(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_INIT_CALLBACK_VTABLE_EPHEMERALSTREAMCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_INIT_CALLBACK_VTABLE_EPHEMERALSTREAMCALLBACK
void uniffi_p2panda_ffi_fn_init_callback_vtable_ephemeralstreamcallback(UniffiVTableCallbackInterfaceEphemeralStreamCallback* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EPHEMERALSTREAMCALLBACK_ON_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EPHEMERALSTREAMCALLBACK_ON_MESSAGE
void uniffi_p2panda_ffi_fn_method_ephemeralstreamcallback_on_message(uint64_t ptr, uint64_t message, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_NODE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_NODE
uint64_t uniffi_p2panda_ffi_fn_clone_node(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_NODE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_NODE
void uniffi_p2panda_ffi_fn_free_node(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_NODE_SPAWN
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CONSTRUCTOR_NODE_SPAWN
uint64_t uniffi_p2panda_ffi_fn_constructor_node_spawn(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODE_EPHEMERAL_STREAM
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODE_EPHEMERAL_STREAM
uint64_t uniffi_p2panda_ffi_fn_method_node_ephemeral_stream(uint64_t ptr, uint64_t topic, uint64_t on_message
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODE_ID
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODE_ID
uint64_t uniffi_p2panda_ffi_fn_method_node_id(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODE_INSERT_BOOTSTRAP
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODE_INSERT_BOOTSTRAP
uint64_t uniffi_p2panda_ffi_fn_method_node_insert_bootstrap(uint64_t ptr, uint64_t node_id, uint64_t relay_url
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODE_NETWORK_ID
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODE_NETWORK_ID
uint64_t uniffi_p2panda_ffi_fn_method_node_network_id(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODE_STREAM
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODE_STREAM
uint64_t uniffi_p2panda_ffi_fn_method_node_stream(uint64_t ptr, uint64_t topic, uint64_t callback
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODE_STREAM_FROM
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_NODE_STREAM_FROM
uint64_t uniffi_p2panda_ffi_fn_method_node_stream_from(uint64_t ptr, uint64_t topic, RustBuffer from, uint64_t callback
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_TOPICSTREAMCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_TOPICSTREAMCALLBACK
uint64_t uniffi_p2panda_ffi_fn_clone_topicstreamcallback(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_TOPICSTREAMCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_TOPICSTREAMCALLBACK
void uniffi_p2panda_ffi_fn_free_topicstreamcallback(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_INIT_CALLBACK_VTABLE_TOPICSTREAMCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_INIT_CALLBACK_VTABLE_TOPICSTREAMCALLBACK
void uniffi_p2panda_ffi_fn_init_callback_vtable_topicstreamcallback(UniffiVTableCallbackInterfaceTopicStreamCallback* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_TOPICSTREAMCALLBACK_ON_EVENT
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_TOPICSTREAMCALLBACK_ON_EVENT
void uniffi_p2panda_ffi_fn_method_topicstreamcallback_on_event(uint64_t ptr, RustBuffer event, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_TOPICSTREAMCALLBACK_ON_ERROR
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_TOPICSTREAMCALLBACK_ON_ERROR
void uniffi_p2panda_ffi_fn_method_topicstreamcallback_on_error(uint64_t ptr, RustBuffer error, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_TOPICSTREAMCALLBACK_ON_OPERATION
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_TOPICSTREAMCALLBACK_ON_OPERATION
void uniffi_p2panda_ffi_fn_method_topicstreamcallback_on_operation(uint64_t ptr, uint64_t processed, RustBuffer source, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_EVENT
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_EVENT
uint64_t uniffi_p2panda_ffi_fn_clone_event(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_EVENT
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_EVENT
void uniffi_p2panda_ffi_fn_free_event(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EVENT_BODY
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EVENT_BODY
RustBuffer uniffi_p2panda_ffi_fn_method_event_body(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EVENT_HEADER
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EVENT_HEADER
uint64_t uniffi_p2panda_ffi_fn_method_event_header(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EVENT_IS_COMPLETED
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EVENT_IS_COMPLETED
int8_t uniffi_p2panda_ffi_fn_method_event_is_completed(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EVENT_IS_FAILED
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_EVENT_IS_FAILED
int8_t uniffi_p2panda_ffi_fn_method_event_is_failed(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_PROCESSEDOPERATION
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_PROCESSEDOPERATION
uint64_t uniffi_p2panda_ffi_fn_clone_processedoperation(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_PROCESSEDOPERATION
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_PROCESSEDOPERATION
void uniffi_p2panda_ffi_fn_free_processedoperation(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PROCESSEDOPERATION_ACK
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PROCESSEDOPERATION_ACK
uint64_t uniffi_p2panda_ffi_fn_method_processedoperation_ack(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PROCESSEDOPERATION_AUTHOR
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PROCESSEDOPERATION_AUTHOR
uint64_t uniffi_p2panda_ffi_fn_method_processedoperation_author(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PROCESSEDOPERATION_ID
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PROCESSEDOPERATION_ID
uint64_t uniffi_p2panda_ffi_fn_method_processedoperation_id(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PROCESSEDOPERATION_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PROCESSEDOPERATION_MESSAGE
RustBuffer uniffi_p2panda_ffi_fn_method_processedoperation_message(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PROCESSEDOPERATION_PROCESSED
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PROCESSEDOPERATION_PROCESSED
uint64_t uniffi_p2panda_ffi_fn_method_processedoperation_processed(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PROCESSEDOPERATION_TIMESTAMP
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PROCESSEDOPERATION_TIMESTAMP
uint64_t uniffi_p2panda_ffi_fn_method_processedoperation_timestamp(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PROCESSEDOPERATION_TOPIC
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_PROCESSEDOPERATION_TOPIC
uint64_t uniffi_p2panda_ffi_fn_method_processedoperation_topic(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_TOPICSTREAM
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_CLONE_TOPICSTREAM
uint64_t uniffi_p2panda_ffi_fn_clone_topicstream(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_TOPICSTREAM
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_FREE_TOPICSTREAM
void uniffi_p2panda_ffi_fn_free_topicstream(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_TOPICSTREAM_ACK
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_TOPICSTREAM_ACK
uint64_t uniffi_p2panda_ffi_fn_method_topicstream_ack(uint64_t ptr, uint64_t message_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_TOPICSTREAM_PRUNE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_TOPICSTREAM_PRUNE
uint64_t uniffi_p2panda_ffi_fn_method_topicstream_prune(uint64_t ptr, RustBuffer message
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_TOPICSTREAM_PUBLISH
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_TOPICSTREAM_PUBLISH
uint64_t uniffi_p2panda_ffi_fn_method_topicstream_publish(uint64_t ptr, RustBuffer message
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_TOPICSTREAM_TOPIC
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_FN_METHOD_TOPICSTREAM_TOPIC
uint64_t uniffi_p2panda_ffi_fn_method_topicstream_topic(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_p2panda_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_p2panda_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUSTBUFFER_FREE
void ffi_p2panda_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_p2panda_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_U8
void ffi_p2panda_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_U8
void ffi_p2panda_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_U8
void ffi_p2panda_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_p2panda_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_I8
void ffi_p2panda_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_I8
void ffi_p2panda_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_I8
void ffi_p2panda_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_p2panda_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_U16
void ffi_p2panda_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_U16
void ffi_p2panda_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_U16
void ffi_p2panda_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_p2panda_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_I16
void ffi_p2panda_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_I16
void ffi_p2panda_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_I16
void ffi_p2panda_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_p2panda_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_U32
void ffi_p2panda_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_U32
void ffi_p2panda_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_U32
void ffi_p2panda_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_p2panda_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_I32
void ffi_p2panda_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_I32
void ffi_p2panda_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_I32
void ffi_p2panda_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_p2panda_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_U64
void ffi_p2panda_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_U64
void ffi_p2panda_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_U64
void ffi_p2panda_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_p2panda_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_I64
void ffi_p2panda_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_I64
void ffi_p2panda_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_I64
void ffi_p2panda_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_p2panda_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_F32
void ffi_p2panda_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_F32
void ffi_p2panda_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_F32
void ffi_p2panda_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_p2panda_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_F64
void ffi_p2panda_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_F64
void ffi_p2panda_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_F64
void ffi_p2panda_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_p2panda_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_p2panda_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_p2panda_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_p2panda_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_p2panda_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_POLL_VOID
void ffi_p2panda_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_p2panda_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_FREE_VOID
void ffi_p2panda_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_p2panda_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_ACK_POLICY
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_ACK_POLICY
uint16_t uniffi_p2panda_ffi_checksum_method_nodebuilder_ack_policy(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_BIND_IP_V4
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_BIND_IP_V4
uint16_t uniffi_p2panda_ffi_checksum_method_nodebuilder_bind_ip_v4(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_BIND_IP_V6
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_BIND_IP_V6
uint16_t uniffi_p2panda_ffi_checksum_method_nodebuilder_bind_ip_v6(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_BIND_PORT_V4
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_BIND_PORT_V4
uint16_t uniffi_p2panda_ffi_checksum_method_nodebuilder_bind_port_v4(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_BIND_PORT_V6
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_BIND_PORT_V6
uint16_t uniffi_p2panda_ffi_checksum_method_nodebuilder_bind_port_v6(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_BOOTSTRAP
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_BOOTSTRAP
uint16_t uniffi_p2panda_ffi_checksum_method_nodebuilder_bootstrap(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_DATABASE_URL
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_DATABASE_URL
uint16_t uniffi_p2panda_ffi_checksum_method_nodebuilder_database_url(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_MDNS_MODE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_MDNS_MODE
uint16_t uniffi_p2panda_ffi_checksum_method_nodebuilder_mdns_mode(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_NETWORK_ID
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_NETWORK_ID
uint16_t uniffi_p2panda_ffi_checksum_method_nodebuilder_network_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_PRIVATE_KEY
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_PRIVATE_KEY
uint16_t uniffi_p2panda_ffi_checksum_method_nodebuilder_private_key(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_RELAY_URL
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_RELAY_URL
uint16_t uniffi_p2panda_ffi_checksum_method_nodebuilder_relay_url(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_SPAWN
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODEBUILDER_SPAWN
uint16_t uniffi_p2panda_ffi_checksum_method_nodebuilder_spawn(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_CURSOR_NAME
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_CURSOR_NAME
uint16_t uniffi_p2panda_ffi_checksum_method_cursor_name(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HASH_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HASH_TO_BYTES
uint16_t uniffi_p2panda_ffi_checksum_method_hash_to_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HASH_TO_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HASH_TO_HEX
uint16_t uniffi_p2panda_ffi_checksum_method_hash_to_hex(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_BACKLINK
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_BACKLINK
uint16_t uniffi_p2panda_ffi_checksum_method_header_backlink(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_HASH
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_HASH
uint16_t uniffi_p2panda_ffi_checksum_method_header_hash(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_LOG_ID
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_LOG_ID
uint16_t uniffi_p2panda_ffi_checksum_method_header_log_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_PAYLOAD_HASH
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_PAYLOAD_HASH
uint16_t uniffi_p2panda_ffi_checksum_method_header_payload_hash(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_PAYLOAD_SIZE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_PAYLOAD_SIZE
uint16_t uniffi_p2panda_ffi_checksum_method_header_payload_size(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_PRUNE_FLAG
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_PRUNE_FLAG
uint16_t uniffi_p2panda_ffi_checksum_method_header_prune_flag(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_PUBLIC_KEY
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_PUBLIC_KEY
uint16_t uniffi_p2panda_ffi_checksum_method_header_public_key(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_SEQ_NUM
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_SEQ_NUM
uint16_t uniffi_p2panda_ffi_checksum_method_header_seq_num(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_SIGNATURE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_SIGNATURE
uint16_t uniffi_p2panda_ffi_checksum_method_header_signature(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_TIMESTAMP
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_TIMESTAMP
uint16_t uniffi_p2panda_ffi_checksum_method_header_timestamp(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_VERSION
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_HEADER_VERSION
uint16_t uniffi_p2panda_ffi_checksum_method_header_version(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NETWORKID_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NETWORKID_TO_BYTES
uint16_t uniffi_p2panda_ffi_checksum_method_networkid_to_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NETWORKID_TO_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NETWORKID_TO_HEX
uint16_t uniffi_p2panda_ffi_checksum_method_networkid_to_hex(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PRIVATEKEY_PUBLIC_KEY
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PRIVATEKEY_PUBLIC_KEY
uint16_t uniffi_p2panda_ffi_checksum_method_privatekey_public_key(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PRIVATEKEY_SIGN
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PRIVATEKEY_SIGN
uint16_t uniffi_p2panda_ffi_checksum_method_privatekey_sign(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PRIVATEKEY_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PRIVATEKEY_TO_BYTES
uint16_t uniffi_p2panda_ffi_checksum_method_privatekey_to_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PRIVATEKEY_TO_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PRIVATEKEY_TO_HEX
uint16_t uniffi_p2panda_ffi_checksum_method_privatekey_to_hex(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PUBLICKEY_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PUBLICKEY_TO_BYTES
uint16_t uniffi_p2panda_ffi_checksum_method_publickey_to_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PUBLICKEY_TO_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PUBLICKEY_TO_HEX
uint16_t uniffi_p2panda_ffi_checksum_method_publickey_to_hex(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PUBLICKEY_VERIFY
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PUBLICKEY_VERIFY
uint16_t uniffi_p2panda_ffi_checksum_method_publickey_verify(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_RELAYURL_TO_STR
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_RELAYURL_TO_STR
uint16_t uniffi_p2panda_ffi_checksum_method_relayurl_to_str(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_SIGNATURE_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_SIGNATURE_TO_BYTES
uint16_t uniffi_p2panda_ffi_checksum_method_signature_to_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_SIGNATURE_TO_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_SIGNATURE_TO_HEX
uint16_t uniffi_p2panda_ffi_checksum_method_signature_to_hex(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_TOPICID_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_TOPICID_TO_BYTES
uint16_t uniffi_p2panda_ffi_checksum_method_topicid_to_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_TOPICID_TO_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_TOPICID_TO_HEX
uint16_t uniffi_p2panda_ffi_checksum_method_topicid_to_hex(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EPHEMERALMESSAGE_AUTHOR
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EPHEMERALMESSAGE_AUTHOR
uint16_t uniffi_p2panda_ffi_checksum_method_ephemeralmessage_author(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EPHEMERALMESSAGE_BODY
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EPHEMERALMESSAGE_BODY
uint16_t uniffi_p2panda_ffi_checksum_method_ephemeralmessage_body(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EPHEMERALMESSAGE_TIMESTAMP
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EPHEMERALMESSAGE_TIMESTAMP
uint16_t uniffi_p2panda_ffi_checksum_method_ephemeralmessage_timestamp(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EPHEMERALMESSAGE_TOPIC
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EPHEMERALMESSAGE_TOPIC
uint16_t uniffi_p2panda_ffi_checksum_method_ephemeralmessage_topic(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EPHEMERALSTREAM_PUBLISH
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EPHEMERALSTREAM_PUBLISH
uint16_t uniffi_p2panda_ffi_checksum_method_ephemeralstream_publish(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EPHEMERALSTREAM_TOPIC
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EPHEMERALSTREAM_TOPIC
uint16_t uniffi_p2panda_ffi_checksum_method_ephemeralstream_topic(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EPHEMERALSTREAMCALLBACK_ON_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EPHEMERALSTREAMCALLBACK_ON_MESSAGE
uint16_t uniffi_p2panda_ffi_checksum_method_ephemeralstreamcallback_on_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODE_EPHEMERAL_STREAM
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODE_EPHEMERAL_STREAM
uint16_t uniffi_p2panda_ffi_checksum_method_node_ephemeral_stream(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODE_ID
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODE_ID
uint16_t uniffi_p2panda_ffi_checksum_method_node_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODE_INSERT_BOOTSTRAP
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODE_INSERT_BOOTSTRAP
uint16_t uniffi_p2panda_ffi_checksum_method_node_insert_bootstrap(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODE_NETWORK_ID
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODE_NETWORK_ID
uint16_t uniffi_p2panda_ffi_checksum_method_node_network_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODE_STREAM
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODE_STREAM
uint16_t uniffi_p2panda_ffi_checksum_method_node_stream(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODE_STREAM_FROM
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_NODE_STREAM_FROM
uint16_t uniffi_p2panda_ffi_checksum_method_node_stream_from(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_TOPICSTREAMCALLBACK_ON_EVENT
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_TOPICSTREAMCALLBACK_ON_EVENT
uint16_t uniffi_p2panda_ffi_checksum_method_topicstreamcallback_on_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_TOPICSTREAMCALLBACK_ON_ERROR
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_TOPICSTREAMCALLBACK_ON_ERROR
uint16_t uniffi_p2panda_ffi_checksum_method_topicstreamcallback_on_error(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_TOPICSTREAMCALLBACK_ON_OPERATION
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_TOPICSTREAMCALLBACK_ON_OPERATION
uint16_t uniffi_p2panda_ffi_checksum_method_topicstreamcallback_on_operation(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EVENT_BODY
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EVENT_BODY
uint16_t uniffi_p2panda_ffi_checksum_method_event_body(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EVENT_HEADER
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EVENT_HEADER
uint16_t uniffi_p2panda_ffi_checksum_method_event_header(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EVENT_IS_COMPLETED
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EVENT_IS_COMPLETED
uint16_t uniffi_p2panda_ffi_checksum_method_event_is_completed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EVENT_IS_FAILED
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_EVENT_IS_FAILED
uint16_t uniffi_p2panda_ffi_checksum_method_event_is_failed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PROCESSEDOPERATION_ACK
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PROCESSEDOPERATION_ACK
uint16_t uniffi_p2panda_ffi_checksum_method_processedoperation_ack(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PROCESSEDOPERATION_AUTHOR
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PROCESSEDOPERATION_AUTHOR
uint16_t uniffi_p2panda_ffi_checksum_method_processedoperation_author(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PROCESSEDOPERATION_ID
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PROCESSEDOPERATION_ID
uint16_t uniffi_p2panda_ffi_checksum_method_processedoperation_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PROCESSEDOPERATION_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PROCESSEDOPERATION_MESSAGE
uint16_t uniffi_p2panda_ffi_checksum_method_processedoperation_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PROCESSEDOPERATION_PROCESSED
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PROCESSEDOPERATION_PROCESSED
uint16_t uniffi_p2panda_ffi_checksum_method_processedoperation_processed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PROCESSEDOPERATION_TIMESTAMP
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PROCESSEDOPERATION_TIMESTAMP
uint16_t uniffi_p2panda_ffi_checksum_method_processedoperation_timestamp(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PROCESSEDOPERATION_TOPIC
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_PROCESSEDOPERATION_TOPIC
uint16_t uniffi_p2panda_ffi_checksum_method_processedoperation_topic(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_TOPICSTREAM_ACK
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_TOPICSTREAM_ACK
uint16_t uniffi_p2panda_ffi_checksum_method_topicstream_ack(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_TOPICSTREAM_PRUNE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_TOPICSTREAM_PRUNE
uint16_t uniffi_p2panda_ffi_checksum_method_topicstream_prune(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_TOPICSTREAM_PUBLISH
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_TOPICSTREAM_PUBLISH
uint16_t uniffi_p2panda_ffi_checksum_method_topicstream_publish(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_TOPICSTREAM_TOPIC
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_METHOD_TOPICSTREAM_TOPIC
uint16_t uniffi_p2panda_ffi_checksum_method_topicstream_topic(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_NODEBUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_NODEBUILDER_NEW
uint16_t uniffi_p2panda_ffi_checksum_constructor_nodebuilder_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_HASH_DIGEST
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_HASH_DIGEST
uint16_t uniffi_p2panda_ffi_checksum_constructor_hash_digest(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_HASH_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_HASH_FROM_BYTES
uint16_t uniffi_p2panda_ffi_checksum_constructor_hash_from_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_HASH_FROM_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_HASH_FROM_HEX
uint16_t uniffi_p2panda_ffi_checksum_constructor_hash_from_hex(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_NETWORKID_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_NETWORKID_FROM_BYTES
uint16_t uniffi_p2panda_ffi_checksum_constructor_networkid_from_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_NETWORKID_FROM_HASH
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_NETWORKID_FROM_HASH
uint16_t uniffi_p2panda_ffi_checksum_constructor_networkid_from_hash(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_NETWORKID_FROM_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_NETWORKID_FROM_HEX
uint16_t uniffi_p2panda_ffi_checksum_constructor_networkid_from_hex(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_NETWORKID_RANDOM
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_NETWORKID_RANDOM
uint16_t uniffi_p2panda_ffi_checksum_constructor_networkid_random(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_PRIVATEKEY_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_PRIVATEKEY_FROM_BYTES
uint16_t uniffi_p2panda_ffi_checksum_constructor_privatekey_from_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_PRIVATEKEY_FROM_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_PRIVATEKEY_FROM_HEX
uint16_t uniffi_p2panda_ffi_checksum_constructor_privatekey_from_hex(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_PRIVATEKEY_GENERATE
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_PRIVATEKEY_GENERATE
uint16_t uniffi_p2panda_ffi_checksum_constructor_privatekey_generate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_PUBLICKEY_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_PUBLICKEY_FROM_BYTES
uint16_t uniffi_p2panda_ffi_checksum_constructor_publickey_from_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_PUBLICKEY_FROM_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_PUBLICKEY_FROM_HEX
uint16_t uniffi_p2panda_ffi_checksum_constructor_publickey_from_hex(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_RELAYURL_FROM_STR
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_RELAYURL_FROM_STR
uint16_t uniffi_p2panda_ffi_checksum_constructor_relayurl_from_str(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_SIGNATURE_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_SIGNATURE_FROM_BYTES
uint16_t uniffi_p2panda_ffi_checksum_constructor_signature_from_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_SIGNATURE_FROM_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_SIGNATURE_FROM_HEX
uint16_t uniffi_p2panda_ffi_checksum_constructor_signature_from_hex(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_TOPICID_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_TOPICID_FROM_BYTES
uint16_t uniffi_p2panda_ffi_checksum_constructor_topicid_from_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_TOPICID_FROM_HASH
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_TOPICID_FROM_HASH
uint16_t uniffi_p2panda_ffi_checksum_constructor_topicid_from_hash(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_TOPICID_FROM_HEX
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_TOPICID_FROM_HEX
uint16_t uniffi_p2panda_ffi_checksum_constructor_topicid_from_hex(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_TOPICID_RANDOM
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_TOPICID_RANDOM
uint16_t uniffi_p2panda_ffi_checksum_constructor_topicid_random(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_NODE_SPAWN
#define UNIFFI_FFIDEF_UNIFFI_P2PANDA_FFI_CHECKSUM_CONSTRUCTOR_NODE_SPAWN
uint16_t uniffi_p2panda_ffi_checksum_constructor_node_spawn(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_P2PANDA_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_P2PANDA_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_p2panda_ffi_uniffi_contract_version(void
    
);
#endif

 void p2panda_ffi_node_cgo_dispatchCallbackInterfaceEphemeralStreamCallbackMethod0(uint64_t uniffi_handle, uint64_t message, void* uniffi_out_return, RustCallStatus* callStatus );
 void p2panda_ffi_node_cgo_dispatchCallbackInterfaceEphemeralStreamCallbackFree(uint64_t handle);
uint64_t p2panda_ffi_node_cgo_dispatchCallbackInterfaceEphemeralStreamCallbackClone(uint64_t handle);
 void p2panda_ffi_node_cgo_dispatchCallbackInterfaceTopicStreamCallbackMethod0(uint64_t uniffi_handle, RustBuffer event, void* uniffi_out_return, RustCallStatus* callStatus );
 void p2panda_ffi_node_cgo_dispatchCallbackInterfaceTopicStreamCallbackMethod1(uint64_t uniffi_handle, RustBuffer error, void* uniffi_out_return, RustCallStatus* callStatus );
 void p2panda_ffi_node_cgo_dispatchCallbackInterfaceTopicStreamCallbackMethod2(uint64_t uniffi_handle, uint64_t processed, RustBuffer source, void* uniffi_out_return, RustCallStatus* callStatus );
 void p2panda_ffi_node_cgo_dispatchCallbackInterfaceTopicStreamCallbackFree(uint64_t handle);
uint64_t p2panda_ffi_node_cgo_dispatchCallbackInterfaceTopicStreamCallbackClone(uint64_t handle);

void p2panda_ffi_uniffiFutureContinuationCallback(uint64_t, int8_t);
void p2panda_ffi_uniffiFreeGorutine(uint64_t);
